#line 2 "SRC/verilog_flex.c"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
static yyconst short int yy_accept[329] =
    {   0,
        0,    0,    0,    0,   88,   86,   80,   81,   79,   79,
       86,    1,   79,   79,   79,   77,   79,   79,   79,   74,
       79,   86,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       79,   79,   83,    1,   83,   80,   67,   78,    0,   60,
       82,   85,    0,   77,   64,   62,   66,   63,   65,   74,
       70,   75,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   25,   74,   74,   74,
       74,   74,   74,   39,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   61,   72,

       71,   73,   84,   69,    0,   85,   76,    0,   68,   75,
       74,    3,   74,   74,    6,   74,   74,   74,   74,   74,
       16,   23,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   37,   38,   74,   74,   74,   43,   74,   74,
       74,   74,   53,   74,   74,   74,   74,   58,    0,   76,
       74,   74,   74,    7,   74,   74,   74,   74,   14,   15,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   35,   74,   74,   74,   74,
        0,   74,   74,   74,   52,   74,   74,   56,   57,    0,
       74,   74,    5,    8,    9,   74,   74,   74,   74,   74,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   28,
       29,   74,   74,   74,   74,   74,   74,   74,    0,   74,
       74,   74,   74,   74,   55,    0,    0,    2,    4,   74,
       11,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   32,   74,    0,   74,   74,   34,   74,   40,   74,
       74,    0,   74,   74,   74,   74,   74,    0,   47,   10,
       74,   13,   17,   74,   74,   74,   74,   22,   74,   74,
       27,    0,   31,   74,   36,    0,   74,   42,    0,   74,
       48,   74,   50,   51,   74,    0,   12,   74,   74,   74,
       74,   24,   26,    0,   74,    0,   74,    0,   46,   74,

       54,    0,   74,   74,   20,   74,    0,   74,    0,   41,
        0,   49,    0,   74,   74,   21,    0,   74,   44,   45,
        0,   19,   18,    0,   33,   59,   30,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    7,    8,    9,   10,   11,
       11,   12,   11,   11,   11,   11,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   11,   11,   17,
       18,   19,   11,   11,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       11,    1,   11,   21,   22,   23,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   20,   33,   34,   35,   36,
       37,   38,   20,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   11,   48,   11,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    4,
        1,    5,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[335] =
    {   0,
        0,    0,   47,   48,  372,  373,   50,  373,  353,   47,
      330,  373,  360,  373,   45,   54,   48,  350,   53,    0,
      318,    0,   39,   25,  342,   46,   49,   40,  337,   51,
       57,   60,   47,   66,  336,   66,   67,  335,   64,   62,
      314,   84,  373,  373,  348,   98,  342,   95,  327,  373,
      373,    0,   87,  105,  373,  373,  340,  373,  373,    0,
      373,    0,  313,  329,  315,  324,  324,  312,  322,  310,
      319,  308,  320,  307,  309,  308,    0,   85,  317,  315,
      305,  310,   89,    0,  298,  299,  297,  306,  311,  306,
      295,  292,  299,  304,  297,  289,  290,  287,  373,  373,

      373,  373,  373,  373,  295,    0,    0,  104,  373,    0,
      300,    0,  291,  290,    0,  293,  101,  296,  291,  290,
      108,    0,  291,   73,  275,  273,  272,  285,  273,  269,
      283,  281,    0,    0,  270,  283,  278,  301,  270,  277,
      264,  268,    0,  259,  265,  270,  258,    0,  260,    0,
      249,  264,  257,   95,  250,  255,  266,  264,    0,    0,
      264,  245,  258,  248,  246,  259,  241,  242,  256,  247,
      237,  236,  246,  238,  240,    0,  246,  230,  236,  243,
      229,  244,   75,  233,    0,  229,  237,  260,    0,  235,
      222,  225,    0,    0,    0,  226,  231,  219,  223,  216,

      219,  218,  226,  224,  211,  218,  225,  209,  223,    0,
      242,  217,  209,  215,  212,  200,  212,  209,  206,  198,
      207,  211,  188,  194,    0,  192,  204,    0,    0,  189,
        0,  205,  200,  199,  200,  197,  182,  197,  189,  184,
      179,    0,  185,  178,  178,  179,    0,  187,  210,  172,
      184,  181,  182,  163,  169,  130,  179,  174,  373,    0,
      170,    0,    0,  163,  164,  168,  169,    0,  164,  171,
        0,  166,    0,  170,    0,  157,  167,    0,  158,  166,
        0,  168,    0,    0,  164,  160,    0,  157,  164,  159,
      157,    0,    0,  155,  142,  155,  143,  153,    0,  145,

        0,  143,  141,  136,    0,  130,  139,  140,  143,    0,
      145,    0,  143,  134,  141,    0,  140,  131,  373,  373,
      120,    0,    0,  119,    0,  373,  373,  373,  149,  152,
      132,  157,  160,  163
    } ;

static yyconst short int yy_def[335] =
    {   0,
      328,    1,  329,  329,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  330,
      328,  331,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  332,  328,  328,  328,  328,  328,  328,  328,  330,
      328,  333,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  328,  328,

      328,  328,  328,  328,  328,  332,  334,  328,  328,  333,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  328,  334,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      328,  330,  330,  330,  330,  330,  330,  330,  330,  328,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  328,  330,
      330,  330,  330,  330,  330,  328,  328,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  328,  330,  330,  330,  330,  330,  330,
      330,  328,  330,  330,  330,  330,  330,  328,  328,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  328,  330,  330,  330,  328,  330,  330,  328,  330,
      330,  330,  330,  330,  330,  328,  330,  330,  330,  330,
      330,  330,  330,  328,  330,  328,  330,  328,  330,  330,

      330,  328,  330,  330,  330,  330,  328,  330,  328,  330,
      328,  330,  328,  330,  330,  330,  328,  330,  328,  328,
      328,  330,  330,  328,  330,  328,  328,    0,  328,  328,
      328,  328,  328,  328
    } ;

static yyconst short int yy_nxt[423] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,    6,
       14,   14,   15,   16,   16,   16,   17,   18,   19,   20,
       21,    6,   22,   23,   24,   25,   26,   27,   28,   29,
       20,   30,   20,   20,   31,   32,   33,   34,   35,   36,
       37,   20,   38,   39,   40,   20,   20,   41,   42,    8,
        8,   46,   66,   46,   44,   44,   51,   52,   45,   45,
       48,   48,   48,   53,   55,   56,   67,   54,   54,   54,
       58,   59,   63,   69,   64,   71,   74,   70,   65,   77,
       79,   75,   72,   81,   73,   84,   78,   82,   85,   86,
       92,   89,  100,   80,   95,   96,   83,   97,   98,   46,

      168,   46,   87,   90,  101,   93,  221,   91,   48,   48,
       48,  107,  222,  107,   53,  169,  125,  107,   54,   54,
       54,  126,  127,  107,  155,  128,  108,  133,  107,  134,
      107,  102,  156,  161,  107,   62,  162,  163,  157,  194,
      107,  195,  164,  283,  284,  327,  326,  165,  166,   43,
       43,   43,   43,   43,   60,   60,   60,  106,  325,  106,
      106,  106,  110,  110,  110,  150,  150,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,

      291,  290,  289,  288,  287,  286,  285,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  193,  192,  191,  190,  189,  188,  187,  186,

      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  167,  160,  159,  158,
      154,  153,  152,  151,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  132,
      131,  130,  129,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  109,  105,  104,
      103,   99,   94,   88,   76,   68,   61,   57,   50,   49,
       47,  328,    5,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328
    } ;

static yyconst short int yy_chk[423] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,   24,    7,    3,    4,   15,   15,    3,    4,
       10,   10,   10,   16,   17,   17,   24,   16,   16,   16,
       19,   19,   23,   26,   23,   27,   28,   26,   23,   30,
       31,   28,   27,   32,   27,   33,   30,   32,   33,   34,
       37,   36,   42,   31,   39,   39,   32,   40,   40,   46,

      124,   46,   34,   36,   42,   37,  183,   36,   48,   48,
       48,   53,  183,   53,   54,  124,   78,   53,   54,   54,
       54,   78,   78,   53,  117,   78,   53,   83,  108,   83,
      108,   42,  117,  121,  108,  331,  121,  121,  117,  154,
      108,  154,  121,  256,  256,  324,  321,  121,  121,  329,
      329,  329,  329,  329,  330,  330,  330,  332,  318,  332,
      332,  332,  333,  333,  333,  334,  334,  317,  315,  314,
      313,  311,  309,  308,  307,  306,  304,  303,  302,  300,
      298,  297,  296,  295,  294,  291,  290,  289,  288,  286,
      285,  282,  280,  279,  277,  276,  274,  272,  270,  269,

      267,  266,  265,  264,  261,  258,  257,  255,  254,  253,
      252,  251,  250,  249,  248,  246,  245,  244,  243,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  230,
      227,  226,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      192,  191,  190,  188,  187,  186,  184,  182,  181,  180,
      179,  178,  177,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  158,  157,
      156,  155,  153,  152,  151,  149,  147,  146,  145,  144,

      142,  141,  140,  139,  138,  137,  136,  135,  132,  131,
      130,  129,  128,  127,  126,  125,  123,  120,  119,  118,
      116,  114,  113,  111,  105,   98,   97,   96,   95,   94,
       93,   92,   91,   90,   89,   88,   87,   86,   85,   82,
       81,   80,   79,   76,   75,   74,   73,   72,   71,   70,
       69,   68,   67,   66,   65,   64,   63,   57,   49,   47,
       45,   41,   38,   35,   29,   25,   21,   18,   13,   11,
        9,    5,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "SRC/verilog_flex.l"
#define INITIAL 0
#line 2 "SRC/verilog_flex.l"
/*
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/ 


#include <stdio.h>
#include <string.h>
#include "types.h"
#include "globals.h"
#include "verilog_bison.h"

/* the define below helps with watching the parser go token by token */
#define MP {if (to_view_parse) {printf("%d %s\n", yylineno, yytext);}}

#define COMMENT 1

#line 612 "SRC/verilog_flex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 39 "SRC/verilog_flex.l"


#line 766 "SRC/verilog_flex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 373 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "SRC/verilog_flex.l"
/*     Keywords */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "SRC/verilog_flex.l"
{ MP; return vALWAYS;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "SRC/verilog_flex.l"
{ MP; return vAND;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "SRC/verilog_flex.l"
{ MP; return vASSIGN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "SRC/verilog_flex.l"
{ MP; return vBEGIN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "SRC/verilog_flex.l"
{ MP; return vCASE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "SRC/verilog_flex.l"
{ MP; return vDEFAULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "SRC/verilog_flex.l"
{ MP; return vDEFINE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "SRC/verilog_flex.l"
{ MP; return vDEFPARAM;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "SRC/verilog_flex.l"
{ MP; return vELSE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "SRC/verilog_flex.l"
{ MP; return vEND;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "SRC/verilog_flex.l"
{ MP; return vENDCASE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "SRC/verilog_flex.l"
{ MP; return vENDGENERATE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "SRC/verilog_flex.l"
{ MP; return vENDMODULE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "SRC/verilog_flex.l"
{ MP; return vFOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "SRC/verilog_flex.l"
{ MP; return vIF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "SRC/verilog_flex.l"
{ MP; return vGENERATE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "SRC/verilog_flex.l"
{ MP; return vINOUT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "SRC/verilog_flex.l"
{ MP; return vINPUT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "SRC/verilog_flex.l"
{ MP; return vINPUT_SIGNED;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "SRC/verilog_flex.l"
{ MP; return vINTEGER;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "SRC/verilog_flex.l"
{ MP; return vGENVAR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "SRC/verilog_flex.l"
{ MP; return vMODULE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "SRC/verilog_flex.l"
{ MP; return vNAND;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "SRC/verilog_flex.l"
{ MP; return vNEGEDGE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "SRC/verilog_flex.l"
{ MP; return vNOR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "SRC/verilog_flex.l"
{ MP; return vNOT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "SRC/verilog_flex.l"
{ MP; return vOR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "SRC/verilog_flex.l"
{ MP; return vOUTPUT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "SRC/verilog_flex.l"
{ MP; return vPARAMETER;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "SRC/verilog_flex.l"
{ MP; return vPOSEDGE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "SRC/verilog_flex.l"
{ MP; return vREG;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "SRC/verilog_flex.l"
{ MP; return vOUTPUT_REG;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "SRC/verilog_flex.l"
{ MP; return vREG_SIGNED;} 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "SRC/verilog_flex.l"
{ MP; return vSIGNED;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "SRC/verilog_flex.l"
{ MP; return vNOT_SUPPORT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "SRC/verilog_flex.l"
{ MP; return vWIRE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "SRC/verilog_flex.l"
{ MP; return vXNOR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "SRC/verilog_flex.l"
{ MP; return vXOR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "SRC/verilog_flex.l"
{ MP; return vWIRE_SIGNED;}
	YY_BREAK
/* Operators */
case 60:
YY_RULE_SETUP
#line 101 "SRC/verilog_flex.l"
{ MP; return voANDAND;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "SRC/verilog_flex.l"
{ MP; return voOROR;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "SRC/verilog_flex.l"
{ MP; return voLTE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "SRC/verilog_flex.l"
{ MP; return voGTE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "SRC/verilog_flex.l"
{ MP; return voSLEFT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "SRC/verilog_flex.l"
{ MP; return voSRIGHT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "SRC/verilog_flex.l"
{ MP; return voEQUAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "SRC/verilog_flex.l"
{ MP; return voNOTEQUAL;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "SRC/verilog_flex.l"
{ MP; return voCASEEQUAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "SRC/verilog_flex.l"
{ MP; return voCASENOTEQUAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "SRC/verilog_flex.l"
{ MP; return voXNOR;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "SRC/verilog_flex.l"
{ MP; return voXNOR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "SRC/verilog_flex.l"
{ MP; return voNAND;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "SRC/verilog_flex.l"
{ MP; return voNOR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "SRC/verilog_flex.l"
{ MP; yylval.id_name = strdup(yytext); return vSYMBOL_ID; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "SRC/verilog_flex.l"
{ MP; yylval.id_name = strdup(yytext); return vSYMBOL_ID; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "SRC/verilog_flex.l"
{ MP; yylval.num_value = strdup(yytext); return vNUMBER_ID; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "SRC/verilog_flex.l"
{ MP; yylval.num_value = strdup(yytext); return vNUMBER_ID; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "SRC/verilog_flex.l"
{ MP; yylval.num_value = strdup(yytext+1); return vDELAY_ID; }
	YY_BREAK
/* return operators */
case 79:
YY_RULE_SETUP
#line 123 "SRC/verilog_flex.l"
{ MP; return yytext[0]; }
	YY_BREAK
/* general stuff */
case 80:
YY_RULE_SETUP
#line 126 "SRC/verilog_flex.l"
{ /* ignore spaces */ continue; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 127 "SRC/verilog_flex.l"
{/* catch lines */ yylineno++; continue; }
	YY_BREAK
/* Get the comments */
case 82:
YY_RULE_SETUP
#line 130 "SRC/verilog_flex.l"
{ /* catch comments */ MP; BEGIN COMMENT; continue; /* means to go into a state where we eat everything for comments*/ }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 131 "SRC/verilog_flex.l"
{ continue; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 132 "SRC/verilog_flex.l"
{ BEGIN 0; continue; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 133 "SRC/verilog_flex.l"
{ MP; continue; }  
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 135 "SRC/verilog_flex.l"
{ printf("Missing verilog.l rule: Default rule invoked in state %d: \"%s\"\n", YY_START, yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 136 "SRC/verilog_flex.l"
ECHO;
	YY_BREAK
#line 1288 "SRC/verilog_flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 328);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 136 "SRC/verilog_flex.l"

